### ISSUE TITLE
Request for Local Setup Instructions

### ISSUE THREAD

**Issue by edengby** [papauschek/crossword-puzzle-maker#3]
Hi there! 👋

First of all, thank you for sharing this amazing project! I've been exploring the **Crossword Puzzle Maker** and truly appreciate the effort and creativity behind it.

I was hoping you could kindly provide some instructions for running the project locally? While I was able to clone and build it, I ran into some issues with setting up the environment to run it smoothly.

I tried using ChatGPT and successfully built the project, but I’m unsure about how to run it correctly. 
When I open the HTML file, I encounter the following error:

```
PuzzleGenerator.scala:17 Uncaught SecurityError: Failed to construct 'Worker': Script at 'crossword-puzzle-maker-master/docs/js/worker.js' cannot be accessed from origin 'null'.
    at new $c_Lcom_papauschek_ui_PuzzleGenerator$ (PuzzleGenerator.scala:17:57)
    at $m_Lcom_papauschek_ui_PuzzleGenerator$ (PuzzleGenerator.scala:9:8)
    at $c_Lcom_papauschek_ui_MainPage.generateSolution__V (MainPage.scala:55:5)
    at HTMLButtonElement.<anonymous> (MainPage.scala:43:67)
```

Any guidance or a quick setup guide would be incredibly helpful for contributors and users like myself who are excited to dive deeper into the project.

Thanks again for your hard work, and looking forward to your response! 🙏

Best regards,  
Eden

**Comment by papauschek** [comment]
Hi, thx for checking it out ;)

Seems like you are running this application by opening the file `docs/index.html` directly in the browser, correct?

Unfortunately, this app needs Web Workers to run in the browser. Most browsers (e.g. Chrome) disallow running web workers on files loaded from the local filesystem.

So you need some small local web server to serve the `docs` folder, and then you're good to go. Some IDEs like IntelliJ have a small web server included.

**Comment by edengby** [comment]
What is the server you used?
I never ran scala stack. How I should run it? Can you describe your server configuration and prompts for start?
Thabk you for the quick reply!

**Comment by papauschek** [comment]
So I actually just use the IntelliJ feature of opening a file in the browser, e.g. right clicking "index.html" => "Open In" => "Browser".

This automatically starts a webserver in the background and opens the app.

(Note: none of this has anything to do with the Scala stack. At this point, you just have a javascript application and are just trying to run that)

**Comment by edengby** [comment]
Thanks! It worked!
What GitHub actions did you use in order to deploy it?

**Comment by papauschek** [comment]
Good to hear :)

See here: https://github.com/papauschek/crossword-puzzle-maker/blob/master/.github/workflows/scala.yml

As you can see in the file, it uses `actions/deploy-pages@v4` after uploading it in the build step with  `actions/upload-artifact@v4`.
